# Setup
title:               Journal
tagline:             '@OneBigBot'
description:         'Computer science, un-artificial intelligence and some math.'
url:                 https://onebigbot.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Winfred Selwyn Ooh
  url:               onebigbot.com
  email:             winfred@onebigbot.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
